-- PEN social features: following, feed interactions, notifications, and separate connections.
-- Run this migration in Supabase SQL Editor before enabling the UI.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  first_name text,
  last_name text,
  avatar_url text,
  bio text,
  created_at timestamptz not null default now()
);

create table if not exists public.follows (
  follower_id uuid not null references public.profiles(id) on delete cascade,
  following_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (follower_id, following_id),
  constraint follows_no_self_follow check (follower_id <> following_id)
);

create index if not exists follows_following_id_idx on public.follows(following_id);
create index if not exists follows_follower_id_idx on public.follows(follower_id);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  recipient_id uuid not null references public.profiles(id) on delete cascade,
  actor_id uuid references public.profiles(id) on delete set null,
  type text not null check (type in ('follow','like','comment','save','share','connect')),
  post_id bigint,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists notifications_recipient_idx
  on public.notifications(recipient_id, created_at desc);

create table if not exists public.posts (
  id bigint generated by default as identity primary key,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null default '',
  image_url text,
  created_at timestamptz not null default now()
);

create index if not exists posts_author_created_idx
  on public.posts(author_id, created_at desc);

create table if not exists public.post_likes (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_comments (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (length(trim(body)) > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.post_saves (
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (post_id, user_id)
);

create table if not exists public.post_shares (
  id bigint generated by default as identity primary key,
  post_id bigint not null references public.posts(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.connections (
  requester_id uuid not null references public.profiles(id) on delete cascade,
  addressee_id uuid not null references public.profiles(id) on delete cascade,
  status text not null default 'pending' check (status in ('pending','accepted','declined','blocked')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (requester_id, addressee_id),
  constraint connections_no_self check (requester_id <> addressee_id)
);

create or replace function public.create_follow_notification()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.notifications(recipient_id, actor_id, type)
  values (new.following_id, new.follower_id, 'follow');
  return new;
end;
$$;

drop trigger if exists follows_notification on public.follows;
create trigger follows_notification after insert on public.follows
for each row execute function public.create_follow_notification();

alter table public.profiles enable row level security;
alter table public.follows enable row level security;
alter table public.notifications enable row level security;
alter table public.posts enable row level security;
alter table public.post_likes enable row level security;
alter table public.post_comments enable row level security;
alter table public.post_saves enable row level security;
alter table public.post_shares enable row level security;
alter table public.connections enable row level security;

drop policy if exists profiles_read on public.profiles;
create policy profiles_read on public.profiles for select using (true);
drop policy if exists profiles_update_own on public.profiles;
create policy profiles_update_own on public.profiles for update using (auth.uid() = id);

drop policy if exists follows_read on public.follows;
create policy follows_read on public.follows for select using (true);
drop policy if exists follows_insert_own on public.follows;
create policy follows_insert_own on public.follows for insert with check (auth.uid() = follower_id and follower_id <> following_id);
drop policy if exists follows_delete_own on public.follows;
create policy follows_delete_own on public.follows for delete using (auth.uid() = follower_id);

create policy notifications_read_own on public.notifications for select using (auth.uid() = recipient_id);
create policy notifications_update_own on public.notifications for update using (auth.uid() = recipient_id);

create policy posts_read on public.posts for select using (true);
create policy posts_insert_own on public.posts for insert with check (auth.uid() = author_id);
create policy posts_update_own on public.posts for update using (auth.uid() = author_id);
create policy posts_delete_own on public.posts for delete using (auth.uid() = author_id);

create policy likes_read on public.post_likes for select using (true);
create policy likes_insert_own on public.post_likes for insert with check (auth.uid() = user_id);
create policy likes_delete_own on public.post_likes for delete using (auth.uid() = user_id);
create policy comments_read on public.post_comments for select using (true);
create policy comments_insert_own on public.post_comments for insert with check (auth.uid() = user_id);
create policy comments_update_own on public.post_comments for update using (auth.uid() = user_id);
create policy comments_delete_own on public.post_comments for delete using (auth.uid() = user_id);
create policy saves_read_own on public.post_saves for select using (auth.uid() = user_id);
create policy saves_insert_own on public.post_saves for insert with check (auth.uid() = user_id);
create policy saves_delete_own on public.post_saves for delete using (auth.uid() = user_id);
create policy shares_read on public.post_shares for select using (true);
create policy shares_insert_own on public.post_shares for insert with check (auth.uid() = user_id);
create policy connections_read_participant on public.connections for select using (auth.uid() in (requester_id, addressee_id));
create policy connections_insert_own on public.connections for insert with check (auth.uid() = requester_id and requester_id <> addressee_id);
create policy connections_update_participant on public.connections for update using (auth.uid() in (requester_id, addressee_id));
